### ISSUE TITLE
1. fork situation (2017 Dec 12): on blockexperts + 2. cryptoguru is stuck

### ISSUE THREAD

**Issue by chess-fan** [chess-fan/MCT#15]
I noticed that my hash is not the same as the hash on blockexperts:
* see [block hashes project](https://github.com/chess-fan/blockhashes-of-ChessCoin)
* the forking took place at block 877216
* that must have been at about the time 2017 Dec 12, 22:58

<br><br>

my:
* getblockhash 877256 => 9825298cde92ffa64ea07a20908a9e62e1b64772e6917d9f885dc7244ce31e6d
* getblockhash 877286 => 0fe448381232d4d52e3c8c606dbf08b1d20613f59aec270a58d99d330b2bdadb (Dec 13)

blockexperts:
* 877256 => a8c...0d6
* 877286 => 0f3ae...df5900

<br>

---
<br>

but for this **it is same**:
* getblockhash 877215 => b895a1eeb46bddb311e530345f881bd1114cd4bc4749f633de0c6a177a555c55

<br><br>

todo:
* add more explanation since I have a hint why this may have happened

**Comment by chess-fan** [comment]
edit:
* see also my comment [here](https://bitcointalk.org/index.php?topic=1510517.msg26245536#msg26245536)

---

about 10h ago I noticed that that the net weight jumped
* it was about 800x more than what we had in the last week: about 80 million

right now with this fork situation the net weight I see on my chain is:
* more than 40 million

so I believe that my chain is the "right one" (though there is no right in blockchain, it's all about consensus... but since the net weight now is about the half of the max I observed yesterday it is a good indicator)

more we will know when other users share their block hashes, see [here](https://bitcointalk.org/index.php?topic=1510517.msg26244118#msg26244118)

**Comment by chess-fan** [comment]
confirmed with block explorer crypto4free, they also have the same hash as mine for:
* 877256
* 877286
* 877350 (this is where I am right now in my wallet)

**Comment by chess-fan** [comment]
edit 2h later:
* cryptoguru is still stuck at block 876599 :-(

---

and the block explorer cryptoguru seems stuck 
* its block height is currently at 876599 (Dec 12, 13:50)
* e.g. I am now at 877358

**Comment by chess-fan** [comment]
informed blockexperts, see [here](https://twitter.com/loverofchess/status/940848099379089408)

**Comment by chess-fan** [comment]
blockexperts is now also stuck:
* 877534 (creation time about 6h ago)
* I am on: 877666

**Comment by ghost** [comment]
Ticket is opened [https://support.blockexperts.com/tickets.php?id=741](https://support.blockexperts.com/tickets.php?id=741l)

**Comment by ghost** [comment]
Download ChessCoin_bootstrap_blk85685_Dec.1.2017 [https://mega.nz/#!BAE2hACZ!DmQLuXWWT2HcF6Rek4p3P8WU22HvFgm0pSuKXf3NUZk](https://mega.nz/#!BAE2hACZ!DmQLuXWWT2HcF6Rek4p3P8WU22HvFgm0pSuKXf3NUZk) and synced it completely!

**Comment by ZzzzeyeZzzz** [comment]
Ticket opened by [cryptoguru.tk](url) - Attention Two accounts!!!
[http://cryptoguru.tk/Faucet/index.php?Currency=CHESS](url)
[https://bitcointalk.org/index.php?action=profile;u=1171856](url)  User “Cryptoguru.tk” 
- Note on fork, new website and Download bootstrap
[https://bitcointalk.org/index.php?action=profile;u=188159](url) User “GrinZ”
- Note on fork and Download bootstrap

**Comment by ghost** [comment]
Ticket opened [http://cryptoguru.tk/](http://cryptoguru.tk/) Attention Two accounts!!!
[http://cryptoguru.tk/Faucet/index.php?Currency=CHESS](http://cryptoguru.tk/Faucet/index.php?Currency=CHESS)

[https://bitcointalk.org/index.php?action=profile;u=1171856](https://bitcointalk.org/index.php?action=profile;u=1171856)  User “Cryptoguru.tk” 
- Note on fork, new website and Download bootstrap

[https://bitcointalk.org/index.php?action=profile;u=188159](https://bitcointalk.org/index.php?action=profile;u=188159) User “GrinZ”
- Note on fork and Download bootstrap

**Comment by ghost** [comment]
Exchanges tested:
[https://yobit.io/en/](https://yobit.io/en/) on the right chain - Deposit and withdrawal :-)
Deposit ID: 07e196b06d1bfc57c2896b2e346188a3c7f18e53059b6a29fcda942af2e6db05 :-)
Withdrawal ID: 19bd5ad6fdc19f5e6ef00fc2bf14f61b957602b9bdd7b62d22357e58f165efcf :-)

[https://www.cryptopia.co.nz](https://www.cryptopia.co.nz) on the right chain - Deposit and withdrawal :-) 
Deposit ID: b1e2ef3b0243b354448cfcf116d20bd91aa856de0658621932e6f6fae32b4882 :-)
Withdrawal ID: 1546c0e293d2ca59e28050ec5f3ce6b564608ac23661cf169ce3228c0ec2fb20 :-)

[https://novaexchange.com](https://novaexchange.com) on the right chain - Withdrawal :-)
Generally no more deposits possible (Will close 2018-03-31)
Withdrawal should be possible but not tested (No ChessCoins there) Current height | 879114)

https://www.coinexchange.io/ No Blockchain/Deposits/Withdrawals since Oct.23.2017 - no Feedback support

**Comment by ghost** [comment]
[https://www.blockexperts.com/chess# ](https://www.blockexperts.com/chess# ) is back on the right chain :-)

**Comment by chess-fan** [comment]
> https://www.blockexperts.com/chess# is back on the right chain :-)

thank you, @ZzzzeyeZzzz 
also for the exchange tests

I'll close this task now
* (once cryptoguru works reliably, I get mostly a blank page there, and they still are not synced until then, I make a new issue for that)
